---
version: 2
plan:
  project-key: QA
  key: HTTPBIN
  name: httpbin.agrd.dev - deploy

variables:
  dockerNode: node:22-slim

stages:
  - Deploy:
      jobs:
        - Deploy

Deploy:
  docker:
    image: ${bamboo.dockerNode}
  key: 'WORKER'
  other:
    clean-working-dir: true
  requirements:
    - 'adg-docker': 'true'
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: 'SHELL'
        scripts:
          - |
            set -e -f -u -x

            npm install
            npm run lint
            npm run test
            npm run build

            CLOUDFLARE_API_TOKEN=${bamboo.cloudflareWorkersDeployerTokenPassword} \
              CLOUDFLARE_ACCOUNT_ID=${bamboo.cloudflareWorkerDeployerAccountID} \
              npx wrangler deploy --route "httpbin.agrd.dev/*"

other:
  concurrent-build-plugin: system-default

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

branch-overrides:
  - '^((?!master).)*$':
      # for branched other than 'master' we run no stages
      stages: []

labels: []
